### ISSUE TITLE
How to fix error: Cannot find module '/storage/emulated/0/Download/invite-manager-bot-master/bin/bot.js'

### ISSUE THREAD

**Issue by lixorhaxz** [SideProjectGuys/invite-manager-bot#108]
![Screenshot_2019-07-03-14-04-42-710_com termux](https://user-images.githubusercontent.com/47329758/60567105-864a0380-9d9b-11e9-94a0-4bc054b86431.png)

**Comment by Valandur** [comment]
What environment are you trying to run our bot on?
