### ISSUE TITLE
Is the doc auto-generated?

### ISSUE THREAD

**Issue by Androz2091** [SideProjectGuys/invite-manager-bot#125]
Hello,
I see some bugs in the docs, for example here:

![Capture d’écran 2019-11-04 à 17 46 36](https://user-images.githubusercontent.com/42497995/68139811-17d4a800-ff2b-11e9-8454-c7501b0ff27b.png)

Can I fix them by editing the files and submitting a pull request or the docs are auto-generated, so I need to update a language file instead of the docs files directly?

**Comment by Androz2091** [comment]
Okay, sorry for disturbing you. Languages files found 😄
I'll open a pr when I'll have the time

**Comment by Valandur** [comment]
Although we have the language files inside the project, we import the translations from [Transifex](https://www.transifex.com/sideprojectguys/invitemanager-bot/translate/). If you would like to help translate please check there (you can signup for free, and join our public project to start adding / correcting translations)

**Comment by Androz2091** [comment]
Thank you, I translated some sentences (and I will translate more in the future). How can I get the translator role in the Discord?
