### ISSUE TITLE
File not found.

### ISSUE THREAD

**Issue by YajTPG** [SideProjectGuys/invite-manager-bot#131]
Can someone help me with this, please?

https://prnt.sc/qvip0k

**Comment by YajTPG** [comment]
Whenever i do npm install, it gives the ERR in the last of the given photo

**Comment by Valandur** [comment]
Try with the newest version of the bot, and using nodejs v12

**Comment by PossibleLuck** [comment]
Same issue here, using nodejs v12

**Comment by Valandur** [comment]
Are you still having this issue? What versions of NodeJS and NPM are you using exactly?

**Comment by YajTPG** [comment]
I'm using the latest ones.

**Comment by Valandur** [comment]
To me that looks like a windows specific error, have you tried on another operating system?
