### ISSUE TITLE
Where should I put my bot token???

### ISSUE THREAD

**Issue by yoyo998** [SideProjectGuys/invite-manager-bot#132]
I followed the guide, don't know where to put the bot token, only put client ID??

	"devToken": "",
	"sentryDsn": "",
	"bot": {
		"type": "regular",
		"ids": {
			"regular": "",
			"pro": ""
		},

**Comment by AndreasGassmann** [comment]
For development, you have use the "devToken" property in the `config.json`.

For production, you will have to add it to the `pm2.json` file.

**Comment by yoyo998** [comment]
devToken as in bots token??
