### ISSUE TITLE
Database not syncing

### ISSUE THREAD

**Issue by maidos** [SideProjectGuys/invite-manager-bot#135]
Yes, im using mariadb and the LEMP stack i installed, does not support mysql. 
IS there anyway to fix this?

**Comment by Valandur** [comment]
What happens when you mention the bot?
Does restarting the bot fix the issue, or do you have to delete the guild settings row in the database?
What MariaDB version is it?

**Comment by maidos** [comment]
Restarting bot works but it does not use the saved configuration
https://i.imgur.com/v7mTQJO.png
https://i.imgur.com/qPhflrm.png
https://i.imgur.com/VlASnlg.png
in guild settings the prefix is example still set for =
but when i do botcommands it says prefix is !
so it basically canot access my old guild settings and i need to redo the configuration and next day it repeats, bot stop responding any commands

| 10.3.22-MariaDB |

**Comment by Valandur** [comment]
We have had a few other people having issues with MariaDB, search the other issues in this repository.
I would personally recommend using MySQL since that is what we use to run the bot.
