### ISSUE TITLE
Self hosting error

### ISSUE THREAD

**Issue by iRoag** [SideProjectGuys/invite-manager-bot#142]
I got an error
`Unhandled Rejection at: Promise Promise {
  <rejected> { Error: Table 'im_1.scheduledactions' doesn't exist`
how i can fix this ?

**Comment by iRoag** [comment]
```
 message: 'Table \'im_1.scheduledactions\' doesn\'t exist',
  code: 'ER_NO_SUCH_TABLE',
  errno: 1146,
  sqlState: '42S02',
  sqlMessage: 'Table \'im_1.scheduledactions\' doesn\'t exist'
```

**Comment by reboxer** [comment]
It clearly tells you that the table `im_1.scheduledactions` doesn't exist in the database.
