### ISSUE TITLE
Error when using npm start

### ISSUE THREAD

**Issue by VogueMist** [SideProjectGuys/invite-manager-bot#143]
Hi I get this error when doing npm start. Any ideas? 
![image](https://user-images.githubusercontent.com/48735695/80119101-29fddd80-8581-11ea-8645-a1043b8013ca.png)

**Comment by Valandur** [comment]
Did you run `npm install`? If you have try running `npm install cross-env` aswell to see if that fixes your issue.

**Comment by VogueMist** [comment]
Hi, I already tried those and when doing `npm install` and doing `npm install cross-env` I still get the same error. Like below.
Thanks
![image](https://user-images.githubusercontent.com/48735695/80209461-0b9fec80-862a-11ea-9ce7-9a95e966fdb3.png)

**Comment by VogueMist** [comment]
I have not used or opened TypeScript before so maybe that is something to do with it? Maybe I am missing an install or something?

**Comment by rjclarkewp007** [comment]
Hi, i am also trying to setup a self hosted option, but i get the same error message when trying to run npm install. Loads of directory missing errors and then the last bit exactly like @VogueMist posted.
What are we doing wrong here?

**Comment by Valandur** [comment]
The error says `No git binary found in $PATH`, which probably means `git` isn't set up properly for your environment.
You can't run the bot before `npm install` is successful.
Please also keep in mind that this is GitHub and meant for actual issues, not tutorials and setup guides.

**Comment by VogueMist** [comment]
Cmon bro please can I have a facecam video on how to set up a git environment. Pleaseeeeeeeeeeee

**Comment by VogueMist** [comment]
Well I tried. Thanks for sorta putting me in the right direction anyway <3

**Comment by VogueMist** [comment]
![image](https://user-images.githubusercontent.com/48735695/80264951-cb725580-868d-11ea-9e4d-64142a0f1442.png)
Is this still because I am a noob?

**Comment by VogueMist** [comment]
> Hi, i am also trying to setup a self hosted option, but i get the same error message when trying to run npm install. Loads of directory missing errors and then the last bit exactly like @VogueMist posted.
> 
> What are we doing wrong here?

I found this https://www.youtube.com/watch?v=J_Clau1bYco bu I get different error some maybe I need to learn something

**Comment by VogueMist** [comment]
@rjclarkewp007 I figured it out. Dm me on discord if you wanna know how. I won’t send it here cause it isn’t for tutorials or help guides- VogueMist#1446

**Comment by AndreasGassmann** [comment]
Glad to hear you figured it out!

It would be nice if you post what you found here so it can help others who have the same issue.

**Comment by rjclarkewp007** [comment]
Hey guys, thanks for the info. Being a noob with this stuff i figured i can learn as i go and i did! :)

@VogueMist thanks for being so eager to assist me as well! Really much appreciated!
I have documented my findings and made a setup guide, but yeah i don't want to post it here seeing as this is not for guides and tutorials. :)
