### ISSUE TITLE
How to add myself as Premium when self hosting

### ISSUE THREAD

**Issue by VogueMist** [SideProjectGuys/invite-manager-bot#144]
Hi, how can I add my guild or myself as a pro user on the bot? Also how can I change the status of the bot? Where is the file. Thanks

**Comment by VogueMist** [comment]
Also where do I get a PollyURL from for music features?

**Comment by Valandur** [comment]
You should change the `bot`.`type` to `custom` in your `config.json` file.
Polly is only used to announce the next song that is being played. You would also have to setup your own Lavalink server to actually play music.
