### ISSUE TITLE
Request failed with status code 401

### ISSUE THREAD

**Issue by Michel92i** [SideProjectGuys/invite-manager-bot#150]
Hi, when I use !play commands in my self hosted bot I have this error
![image](https://user-images.githubusercontent.com/66451443/83827343-5ce9d400-a6de-11ea-98e8-109ef2a3740b.png)

here is the error: 
`{ Error: Request failed with status code 401
0|npm  |     at createError (/root/Bot/invite-manager-bot/node_modules/axios/lib/core/createError.js:16:15)
0|npm  |     at settle (/root/Bot/invite-manager-bot/node_modules/axios/lib/core/settle.js:17:12)
0|npm  |     at IncomingMessage.handleStreamEnd (/root/Bot/invite-manager-bot/node_modules/axios/lib/adapters/http.js:236:11)
0|npm  |     at IncomingMessage.emit (events.js:203:15)
0|npm  |     at IncomingMessage.EventEmitter.emit (domain.js:448:20)
0|npm  |     at endReadableNT (_stream_readable.js:1143:12)
0|npm  |     at process._tickCallback (internal/process/next_tick.js:63:19)
0|npm  |   config:
0|npm  |    { url:
0|npm  |       'http://api.soundcloud.com/tracks?q=rk&client_id=Vu5tlmvC9eCLFZkxXG32N1yQMfDSAPAA',
0|npm  |      method: 'get',
0|npm  |      headers:
0|npm  |       { Accept: 'application/json, text/plain, */*',
0|npm  |         'User-Agent': 'axios/0.19.2' },
0|npm  |      transformRequest: [ [Function: transformRequest] ],
0|npm  |      transformResponse: [ [Function: transformResponse] ],
0|npm  |      timeout: 0,
0|npm  |      adapter: [Function: httpAdapter],
0|npm  |      xsrfCookieName: 'XSRF-TOKEN',
0|npm  |      xsrfHeaderName: 'X-XSRF-TOKEN',
0|npm  |      maxContentLength: -1,
0|npm  |      validateStatus: [Function: validateStatus],
0|npm  |      data: undefined },
0|npm  |   request:
0|npm  |    ClientRequest {
0|npm  |      domain: null,
0|npm  |      _events:
0|npm  |       [Object: null prototype] {
0|npm  |         socket: [Function],
0|npm  |         abort: [Function],
0|npm  |         aborted: [Function],
0|npm  |         error: [Function],
0|npm  |         timeout: [Function],
0|npm  |         prefinish: [Function: requestOnPrefinish] },
0|npm  |      _eventsCount: 6,
0|npm  |      _maxListeners: undefined,
0|npm  |      output: [],
0|npm  |      outputEncodings: [],
0|npm  |      outputCallbacks: [],
0|npm  |      outputSize: 0,
0|npm  |      writable: true,
0|npm  |      _last: true,
0|npm  |      chunkedEncoding: false,
0|npm  |      shouldKeepAlive: false,
0|npm  |      useChunkedEncodingByDefault: false,
0|npm  |      sendDate: false,
0|npm  |      _removedConnection: false,
0|npm  |      _removedContLen: false,
0|npm  |      _removedTE: false,
0|npm  |      _contentLength: 0,
0|npm  |      _hasBody: true,
0|npm  |      _trailer: '',
0|npm  |      finished: true,
0|npm  |      _headerSent: true,
0|npm  |      socket:
0|npm  |       Socket {
0|npm  |         connecting: false,
0|npm  |         _hadError: false,
0|npm  |         _handle: [TCP],
0|npm  |         _parent: null,
0|npm  |         _host: 'api.soundcloud.com',
0|npm  |         _readableState: [ReadableState],
0|npm  |         readable: true,
0|npm  |         domain: null,
0|npm  |         _events: [Object],
0|npm  |         _eventsCount: 7,
0|npm  |         _maxListeners: undefined,
0|npm  |         _writableState: [WritableState],
0|npm  |         writable: false,
0|npm  |         allowHalfOpen: false,
0|npm  |         _sockname: null,
0|npm  |         _pendingData: null,
0|npm  |         _pendingEncoding: '',
0|npm  |         server: null,
0|npm  |         _server: null,
0|npm  |         parser: null,
0|npm  |         _httpMessage: [Circular],
0|npm  |         [Symbol(asyncId)]: 1013,
0|npm  |         [Symbol(lastWriteQueueSize)]: 0,
0|npm  |         [Symbol(timeout)]: null,
0|npm  |         [Symbol(kBytesRead)]: 0,
0|npm  |         [Symbol(kBytesWritten)]: 0 },
0|npm  |      connection:
0|npm  |       Socket {
0|npm  |         connecting: false,
0|npm  |         _hadError: false,
0|npm  |         _handle: [TCP],
0|npm  |         _parent: null,
0|npm  |         _host: 'api.soundcloud.com',
0|npm  |         _readableState: [ReadableState],
0|npm  |         readable: true,
0|npm  |         domain: null,
0|npm  |         _events: [Object],
0|npm  |         _eventsCount: 7,
0|npm  |         _maxListeners: undefined,
0|npm  |         _writableState: [WritableState],
0|npm  |         writable: false,
0|npm  |         allowHalfOpen: false,
0|npm  |         _sockname: null,
0|npm  |         _pendingData: null,
0|npm  |         _pendingEncoding: '',
0|npm  |         server: null,
0|npm  |         _server: null,
0|npm  |         parser: null,
0|npm  |         _httpMessage: [Circular],
0|npm  |         [Symbol(asyncId)]: 1013,
0|npm  |         [Symbol(lastWriteQueueSize)]: 0,
0|npm  |         [Symbol(timeout)]: null,
0|npm  |         [Symbol(kBytesRead)]: 0,
0|npm  |         [Symbol(kBytesWritten)]: 0 },
0|npm  |      _header:
0|npm  |       'GET /tracks?q=rk&client_id=Vu5tlmvC9eCLFZkxXG32N1yQMfDSAPAA HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.19.2\r\nHost: api.soundcloud.com\r\nConnection: close\r\n\r\n',
0|npm  |      _onPendingData: [Function: noopPendingOutput],
0|npm  |      agent:
0|npm  |       Agent {
0|npm  |         _events: [Object],
0|npm  |         _eventsCount: 1,
0|npm  |         _maxListeners: undefined,
0|npm  |         defaultPort: 80,
0|npm  |         protocol: 'http:',
0|npm  |         options: [Object],
0|npm  |         requests: {},
0|npm  |         sockets: [Object],
0|npm  |         freeSockets: {},
0|npm  |         keepAliveMsecs: 1000,
0|npm  |         keepAlive: false,
0|npm  |         maxSockets: Infinity,
0|npm  |         maxFreeSockets: 256 },
0|npm  |      socketPath: undefined,
0|npm  |      timeout: undefined,
0|npm  |      method: 'GET',
0|npm  |      path: '/tracks?q=rk&client_id=Vu5tlmvC9eCLFZkxXG32N1yQMfDSAPAA',
0|npm  |      _ended: true,
0|npm  |      res:
0|npm  |       IncomingMessage {
0|npm  |         _readableState: [ReadableState],
0|npm  |         readable: false,
0|npm  |         domain: null,
0|npm  |         _events: [Object],
0|npm  |         _eventsCount: 3,
0|npm  |         _maxListeners: undefined,
0|npm  |         socket: [Socket],
0|npm  |         connection: [Socket],
0|npm  |         httpVersionMajor: 1,
0|npm  |         httpVersionMinor: 1,
0|npm  |         httpVersion: '1.1',
0|npm  |         complete: true,
0|npm  |         headers: [Object],
0|npm  |         rawHeaders: [Array],
0|npm  |         trailers: {},
0|npm  |         rawTrailers: [],
0|npm  |         aborted: false,
0|npm  |         upgrade: false,
0|npm  |         url: '',
0|npm  |         method: null,
0|npm  |         statusCode: 401,
0|npm  |         statusMessage: 'Unauthorized',
0|npm  |         client: [Socket],
0|npm  |         _consuming: false,
0|npm  |         _dumped: false,
0|npm  |         req: [Circular],
0|npm  |         responseUrl:
0|npm  |          'http://api.soundcloud.com/tracks?q=rk&client_id=Vu5tlmvC9eCLFZkxXG32N1yQMfDSAPAA',
0|npm  |         redirects: [] },
0|npm  |      aborted: undefined,
0|npm  |      timeoutCb: null,
0|npm  |      upgradeOrConnect: false,
0|npm  |      parser: null,
0|npm  |      maxHeadersCount: null,
0|npm  |      _redirectable:
0|npm  |       Writable {
0|npm  |         _writableState: [WritableState],
0|npm  |         writable: true,
0|npm  |         domain: null,
0|npm  |         _events: [Object],
0|npm  |         _eventsCount: 2,
0|npm  |         _maxListeners: undefined,
0|npm  |         _options: [Object],
0|npm  |         _redirectCount: 0,
0|npm  |         _redirects: [],
0|npm  |         _requestBodyLength: 0,
0|npm  |         _requestBodyBuffers: [],
0|npm  |         _onNativeResponse: [Function],
0|npm  |         _currentRequest: [Circular],
0|npm  |         _currentUrl:
0|npm  |          'http://api.soundcloud.com/tracks?q=rk&client_id=Vu5tlmvC9eCLFZkxXG32N1yQMfDSAPAA' },
0|npm  |      [Symbol(isCorked)]: false,
0|npm  |      [Symbol(outHeadersKey)]:
0|npm  |       [Object: null prototype] { accept: [Array], 'user-agent': [Array], host: [Array] } },
0|npm  |   response:
0|npm  |    { status: 401,
0|npm  |      statusText: 'Unauthorized',
0|npm  |      headers:
0|npm  |       { 'content-length': '0',
0|npm  |         connection: 'close',
0|npm  |         date: 'Fri, 05 Jun 2020 01:36:30 GMT',
0|npm  |         'cache-control': 'private, max-age=0',
0|npm  |         'referrer-policy': 'no-referrer',
0|npm  |         'x-frame-options': 'DENY',
0|npm  |         'x-content-type-options': 'nosniff',
0|npm  |         server: 'am/2',
0|npm  |         vary: 'Origin',
0|npm  |         'x-cache': 'Error from cloudfront',
0|npm  |         via:
0|npm  |          '1.1 b3d672c454c45e15da48dfcb26c8e40f.cloudfront.net (CloudFront)',
0|npm  |         'x-amz-cf-pop': 'CDG50-C1',
0|npm  |         'x-amz-cf-id': 'JaFp0sqahOQxV3aLcTiTjnRC-PE1tBMA5SWQH7x1sfN7AAYIv-XqQQ==' },
0|npm  |      config:
0|npm  |       { url:
0|npm  |          'http://api.soundcloud.com/tracks?q=rk&client_id=Vu5tlmvC9eCLFZkxXG32N1yQMfDSAPAA',
0|npm  |         method: 'get',
0|npm  |         headers: [Object],
0|npm  |         transformRequest: [Array],
0|npm  |         transformResponse: [Array],
0|npm  |         timeout: 0,
0|npm  |         adapter: [Function: httpAdapter],
0|npm  |         xsrfCookieName: 'XSRF-TOKEN',
0|npm  |         xsrfHeaderName: 'X-XSRF-TOKEN',
0|npm  |         maxContentLength: -1,
0|npm  |         validateStatus: [Function: validateStatus],
0|npm  |         data: undefined },
0|npm  |      request:
0|npm  |       ClientRequest {
0|npm  |         domain: null,
0|npm  |         _events: [Object],
0|npm  |         _eventsCount: 6,
0|npm  |         _maxListeners: undefined,
0|npm  |         output: [],
0|npm  |         outputEncodings: [],
0|npm  |         outputCallbacks: [],
0|npm  |         outputSize: 0,
0|npm  |         writable: true,
0|npm  |         _last: true,
0|npm  |         chunkedEncoding: false,
0|npm  |         shouldKeepAlive: false,
0|npm  |         useChunkedEncodingByDefault: false,
0|npm  |         sendDate: false,
0|npm  |         _removedConnection: false,
0|npm  |         _removedContLen: false,
0|npm  |         _removedTE: false,
0|npm  |         _contentLength: 0,
0|npm  |         _hasBody: true,
0|npm  |         _trailer: '',
0|npm  |         finished: true,
0|npm  |         _headerSent: true,
0|npm  |         socket: [Socket],
0|npm  |         connection: [Socket],
0|npm  |         _header:
0|npm  |          'GET /tracks?q=rk&client_id=Vu5tlmvC9eCLFZkxXG32N1yQMfDSAPAA HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.19.2\r\nHost: api.soundcloud.com\r\nConnection: close\r\n\r\n',
0|npm  |         _onPendingData: [Function: noopPendingOutput],
0|npm  |         agent: [Agent],
0|npm  |         socketPath: undefined,
0|npm  |         timeout: undefined,
0|npm  |         method: 'GET',
0|npm  |         path: '/tracks?q=rk&client_id=Vu5tlmvC9eCLFZkxXG32N1yQMfDSAPAA',
0|npm  |         _ended: true,
0|npm  |         res: [IncomingMessage],
0|npm  |         aborted: undefined,
0|npm  |         timeoutCb: null,
0|npm  |         upgradeOrConnect: false,
0|npm  |         parser: null,
0|npm  |         maxHeadersCount: null,
0|npm  |         _redirectable: [Writable],
0|npm  |         [Symbol(isCorked)]: false,
0|npm  |         [Symbol(outHeadersKey)]: [Object] },
0|npm  |      data: '' },
0|npm  |   isAxiosError: true,
0|npm  |   toJSON: [Function] }
`

**Comment by Valandur** [comment]
The bot is currently not setup to support music when self hosting. You have to run your own lavalink server, plus some additional software that have not made public.
Not sure if this will change in the future, as it's quite a bit of work.
