### ISSUE TITLE
Exporting invite database

### ISSUE THREAD

**Issue by MCMrARM** [SideProjectGuys/invite-manager-bot#161]
Hello,
I'm interested in exporting the invite database (`joins` and `inviteCodes` tables) for my premium guild, 450367979310284801. Any format works for me, including a SQL dump. I'm also willing to implement this feature and submit a pull request if there's interest in adding this feature to the bot itself.

Thank you!

**Comment by SyntaxDragon** [comment]
just use the mysql dump tool or google "MySQL/MariaDB export collections"

**Comment by MCMrARM** [comment]
I have no access to the infrastructure as we used the officially hosted bot :/
Yes if I self-hosted it'd be trivial.
