### ISSUE TITLE
How can I disable the bot's Discord custom status?

### ISSUE THREAD

**Issue by XPMai** [SideProjectGuys/invite-manager-bot#178]
I want it to undo/remove the custom status.

Current custom status: `Playing docs.invitemanager.co!`

**Comment by chaun14** [comment]
Remove it from the source code in src/client.ts

**Comment by XPMai** [comment]
> Remove it from the source code in src/client.ts

Which lines should I remove? I scared breaking the code.

And just asking, is it a setting that can be disabled?

**Comment by SyntaxDragon** [comment]
https://github.com/SideProjectGuys/invite-manager-bot/blob/6fea1726e1d2485ba9809017d35411ad817f3c71/src/client.ts#L607-L630
I believe you could just comment these out.

**Comment by ghost** [comment]
Commenting out the public async setactivity makes npm start fail.
Instead just make a backup of current client.ts and delete the following section
![image](https://user-images.githubusercontent.com/70638053/92995769-24446c80-f50f-11ea-9d8b-80290bdbf6ae.png)
If you want to customize it instead of deleting you can replace the "playing" with watching, listening or streaming and the "docs.invitemanager.co!" that follows those lines with whatever you want. This method works, i tested it on a alternate token.

**Comment by SyntaxDragon** [comment]
ah my bad I forget it would do that, but yeah you can always either make it a dummy function or customise it to look how you want, I just leave it as it is since I'm not hosting the docs.

**Comment by XPMai** [comment]
> https://github.com/SideProjectGuys/invite-manager-bot/blob/6fea1726e1d2485ba9809017d35411ad817f3c71/src/client.ts#L607-L630
> 
> 
> I believe you could just comment these out.

```
src/client.ts:369:14 - error TS2339: Property 'setActivity' does not exist on type 'IMClient'.

369     await this.setActivity();
                   ~~~~~~~~~~~

src/client.ts:370:50 - error TS2339: Property 'setActivity' does not exist on type 'IMClient'.

370     this.activityInterval = setInterval(() => this.setActivity(), 1 * 60 * 1000);
                                                       ~~~~~~~~~~~

src/framework/commands/config/botConfig.ts:132:21 - error TS2339: Property 'setActivity' does not exist on type 'IMClient'.

132     await this.client.setActivity();
                          ~~~~~~~~~~~
I get this error:

Found 3 errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! discord-invite-manager@9.8.0 build: `tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the discord-invite-manager@9.8.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2020-09-21T10_29_16_992Z-debug.log
```

**Comment by XPMai** [comment]
Gahh, nvm. It's the `!botConfig` command

Reference: https://github.com/SideProjectGuys/invite-manager-bot/blob/18448a77a33936ba2424d24ac8bc575a0bad15e8/docs/cs/reference/commands.md#botConfig
