### ISSUE TITLE
PLS ONLINE

### ISSUE THREAD

**Issue by DonDoesStuff** [SideProjectGuys/invite-manager-bot#187]
THE BOT IS DOWN BRING HIM BACK IN THE BUILDING PLSSSS

**Comment by chaun14** [comment]
Don't open an issue for that, it's not a problem from the code. 

Maybe consider to pay the invitemanager pro or use another invite tracking bot.

**Comment by DonDoesStuff** [comment]
> Don't open an issue for that, it's not a problem from the code. 
> 
> 
> 
> Maybe consider to pay the invitemanager pro or use another invite tracking bot.

That bot is down too XD

**Comment by chaun14** [comment]
There are few forks online, use one of them

**Comment by kpopdev** [comment]
you can use my clone https://discord.com/oauth2/authorize?client_id=637604212825522176&scope=bot&permissions=66186303

**Comment by DonDoesStuff** [comment]
> you can use my clone https://discord.com/oauth2/authorize?client_id=637604212825522176&scope=bot&permissions=66186303

Ty!

**Comment by xFalcon0** [comment]
Also you can use https://invlogger.chaun14.fr/bot/ : D
