### ISSUE TITLE
the bot does not show invited users, if you restart it then invited users will appear, how to fix this?

### ISSUE THREAD

**Issue by eshkaflex** [SideProjectGuys/invite-manager-bot#189]
private async onGuildMemberAdd(guild: Guild, member: Member) {
		console.log(
			'EVENT(guildMemberAdd):',
			guild.id,
			guild.name,
			member.id,
			member.username + '#' + member.discriminator
		);

I think the error is somewhere here

**Comment by chaun14** [comment]
Add some console.log to know where the problem comes from

**Comment by eshkaflex** [comment]
> 
> 
> Add some console.log to know where the problem comes from

no errors were sent to the console
the required event handler in the tracking subsystem is not called, so the bot does not update the data in the cache, since it cannot react to this event.

**Comment by chaun14** [comment]
does your bot has member intent checked? Otherwise it can't recieve the guildmemberadd or remove event

**Comment by eshkaflex** [comment]
> 
> 
> does your bot has member intent checked? Otherwise it can't recieve the guildmemberadd or remove event

Where i can check it?

**Comment by eshkaflex** [comment]
> 
> 
> does your bot has member intent checked? Otherwise it can't recieve the guildmemberadd or remove event

i fixed it , thx

**Comment by FUCKYOUGITHUBFUCKYOU** [comment]
what did you fix? I have same issue, welcome message not popping up etc, but if you do !invites it shows, only after restart is the count updated though.
