### ISSUE TITLE
!createInvite (Brainstorm)

### ISSUE THREAD

**Issue by AndreasGassmann** [SideProjectGuys/invite-manager-bot#20]
Users can create an invite with a command. The invite should either have a name, purpose or belong to a challenge.

Use case would be to create multiple invites and track where people come from (post reddit link in reddit, dbot link on discordbots, etc etc).

One problem might be that the code has to be attached to a channel. That channel should never be deleted. So mods need to define it (or can we create a hidden channel for us?)

**Comment by Valandur** [comment]
Implemented in 9ecc5d32d56578de2815e0500f44847772bc322b
