### ISSUE TITLE
Some smaller todos

### ISSUE THREAD

**Issue by AndreasGassmann** [SideProjectGuys/invite-manager-bot#51]
- [ ] Self-join counts as a join
- [x] "Time on server" in the leave messages is **always** a few seconds ago.
- [ ] Option to disable/not count joins from users whose accounts were created less than _ time ago.
- [x] DMs don't work
- [ ] Show prefix in welcome message
- [ ] Add a message to be posted in #general after the bot was invited. It should be very short, only say `Your current prefix is !, see commands with !help, to set up join and leave messages do !setup)
- [ ] We might want to make the !setup command easier and move the missing permissions to a !diagnose command (we can still internally call the !diagnose command every time someone does !setup)
- [x] {{prefix}} needs to be replaced in !memberconfig text

**Comment by Valandur** [comment]
Replaced by #102, #103, #104, #105 and #106
